<script setup>
import { onMounted, onUnmounted, ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import {
  ArrowLeft,
  Download,
  MagicStick,
  ThumbsUp,
  ChatLineRound,
} from '@element-plus/icons-vue'
import {
  getReport,
  submitFeedback,
  parseStats,
  statusLabel,
  periodTypeLabel,
} from '../api/reports'
import { markReportRead } from '../services/reportNotice'

const route = useRoute()
const router = useRouter()

const report = ref(null)
const loading = ref(false)
const feedbackRating = ref(null)
const feedbackComment = ref('')
const submitting = ref(false)
let pollTimer = null

const reportId = computed(() => route.params.id)
const isGenerating = computed(() => report.value?.status === 0)
const isReady = computed(() => report.value?.status === 1)
const isFailed = computed(() => report.value?.status === 2)
const isNoData = computed(() => report.value?.status === 3)

const stats = computed(() => report.value ? parseStats(report.value.statsSnapshotJson) : null)

const hourly = computed(() => stats.value?.hourlyDistribution ?? [])
const weekday = computed(() => stats.value?.weekdayDistribution ?? [])
const topTracks = computed(() => (stats.value?.topTracks ?? []).slice(0, 8))
const topArtists = computed(() => (stats.value?.topArtists ?? []).slice(0, 8))

const maxHourly = computed(() => Math.max(1, ...hourly.value))
const maxWeekday = computed(() => Math.max(1, ...weekday.value))

// 24 小时柱状图 path
const hourlyBars = computed(() => {
  const w = 100
  const h = 60
  return hourly.value.map((v, i) => {
    const barH = (v / maxHourly.value) * h
    const x = (i / 24) * w + 0.4
    const y = h - barH
    return { x, y, h: barH, v, label: i }
  })
})

// 周柱状图 path
const weekdayBars = computed(() => {
  const labels = ['一', '二', '三', '四', '五', '六', '日']
  return weekday.value.map((v, i) => {
    const h = 60
    const barH = (v / maxWeekday.value) * h
    const barWidth = 12
    const x = i * (100 / 7) + 2
    return { x, y: h - barH, w: barWidth, h: barH, v, label: labels[i] }
  })
})

// ===== 加载 =====
async function load() {
  loading.value = true
  try {
    report.value = await getReport(reportId.value)
  } catch (err) {
    console.error('加载报告失败:', err)
    ElMessage.error(err.message || '加载失败')
  } finally {
    loading.value = false
  }
}

function startPollingIfNeeded() {
  stopPolling()
  if (isGenerating.value) {
    pollTimer = setInterval(async () => {
      try {
        const latest = await getReport(reportId.value)
        if (latest && latest.status !== 0) {
          report.value = latest
          stopPolling()
          ElMessage.success('报告生成完成')
        }
      } catch { /* ignore */ }
    }, 3000)
  }
}

function stopPolling() {
  if (pollTimer) {
    clearInterval(pollTimer)
    pollTimer = null
  }
}

// ===== 反馈 =====
async function handleFeedback() {
  if (!feedbackRating.value) {
    ElMessage.warning('请先选择赞/踩')
    return
  }
  submitting.value = true
  try {
    await submitFeedback(reportId.value, feedbackRating.value, feedbackComment.value || undefined)
    ElMessage.success('反馈已提交, 感谢!')
    feedbackComment.value = ''
  } catch (err) {
    ElMessage.error(err.message || '提交失败')
  } finally {
    submitting.value = false
  }
}

// ===== 下载 =====
function handleDownload() {
  if (!report.value) return
  const text = formatReportAsText(report.value, stats.value)
  downloadFile(`${report.value.title || '报告'}.md`, text, 'text/markdown;charset=utf-8')
}

function formatReportAsText(r, s) {
  const lines = []
  lines.push(`# ${r.title || r.periodTypeLabel}`)
  lines.push('')
  lines.push(`> 周期: ${r.periodStart} ~ ${r.periodEnd}`)
  lines.push(`> 生成时间: ${r.generatedAt || '生成中'}`)
  lines.push('')
  lines.push('## AI 总结')
  lines.push(r.summary || '（暂无）')
  lines.push('')
  if (r.moodTags && r.moodTags.length > 0) {
    lines.push('## 心情标签')
    lines.push(r.moodTags.map(t => `#${t}`).join(' '))
    lines.push('')
  }
  if (r.highlights && r.highlights.length > 0) {
    lines.push('## 高光时刻')
    r.highlights.forEach((h, i) => lines.push(`${i + 1}. ${h}`))
    lines.push('')
  }
  if (r.recommendations && r.recommendations.length > 0) {
    lines.push('## 推荐收听')
    r.recommendations.forEach((rec, i) => lines.push(`${i + 1}. ${rec}`))
    lines.push('')
  }
  if (s) {
    lines.push('## 数据统计')
    lines.push(`- 总播放: ${s.totalPlays ?? '-'}`)
    lines.push(`- 总时长(分钟): ${Math.round((s.totalDurationSec || 0) / 60)}`)
    lines.push(`- 去重歌曲: ${s.uniqueTracks ?? '-'}`)
    if (s.topTracks && s.topTracks.length > 0) {
      lines.push('')
      lines.push('### TOP 歌曲')
      s.topTracks.slice(0, 10).forEach((t, i) => {
        lines.push(`${i + 1}. ${t.name} (${t.count} 次)`)
      })
    }
  }
  lines.push('')
  lines.push('---')
  lines.push('Generated by Auramix')
  return lines.join('\n')
}

function downloadFile(filename, content, mime) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 100)
}

function back() {
  router.push('/reports')
}

onMounted(async () => {
  await load()
  startPollingIfNeeded()
  // 标记为已读 (清掉顶栏红点)
  if (report.value && report.value.status === 1) {
    markReportRead(report.value.id)
  }
})

onUnmounted(stopPolling)
</script>

<template>
  <div class="report-detail" v-loading="loading">
    <!-- 顶部 -->
    <div class="report-detail__top">
      <el-button :icon="ArrowLeft" link @click="back" class="back-btn">返回列表</el-button>
      <el-button
        v-if="report && isReady"
        type="primary"
        :icon="Download"
        @click="handleDownload"
      >
        下载报告
      </el-button>
    </div>

    <div v-if="report" class="report-detail__content">
      <!-- 头部 -->
      <div class="report-header">
        <div>
          <h1 class="report-header__title">
            {{ report.periodTypeLabel }} ({{ report.periodStart }} ~ {{ report.periodEnd }})
          </h1>
          <p class="report-header__meta">
            <el-tag :type="report.status === 1 ? 'success' : report.status === 0 ? 'warning' : 'info'" size="small" effect="dark">
              {{ statusLabel(report.status) }}
            </el-tag>
            <span v-if="report.generatedAt">生成于 {{ report.generatedAt }}</span>
            <span v-else-if="isGenerating" class="report-header__pending">
              <el-icon class="is-loading"><MagicStick /></el-icon> 正在生成, 自动刷新中...
            </span>
          </p>
        </div>
      </div>

      <!-- 生成中 -->
      <div v-if="isGenerating" class="status-block status-block--pending">
        <el-icon class="is-loading"><MagicStick /></el-icon>
        <p>报告正在生成中, 大约 5~15 秒。页面会自动刷新状态。</p>
      </div>

      <!-- 失败 -->
      <div v-else-if="isFailed" class="status-block status-block--failed">
        <h3>生成失败</h3>
        <p>{{ report.errorMessage || '未知错误' }}</p>
      </div>

      <!-- 无数据 -->
      <div v-else-if="isNoData" class="status-block status-block--empty">
        <h3>本周期暂无听歌数据</h3>
        <p>先在「音乐库」里听点歌, 下个周期再来查看吧。</p>
      </div>

      <!-- 已生成 -->
      <template v-else-if="isReady">
        <!-- AI 总结 -->
        <section class="detail-section">
          <h2 class="detail-section__title">AI 总结</h2>
          <p class="summary-text">{{ report.summary }}</p>
          <div v-if="report.moodTags && report.moodTags.length > 0" class="mood-tags">
            <el-tag
              v-for="(tag, idx) in report.moodTags"
              :key="idx"
              type="primary"
              effect="plain"
              round
            >#{{ tag }}</el-tag>
          </div>
        </section>

        <!-- 高光时刻 + 推荐 -->
        <div class="row-2">
          <section v-if="report.highlights && report.highlights.length > 0" class="detail-section">
            <h2 class="detail-section__title">高光时刻</h2>
            <ul class="bullet-list">
              <li v-for="(h, idx) in report.highlights" :key="idx">{{ h }}</li>
            </ul>
          </section>
          <section v-if="report.recommendations && report.recommendations.length > 0" class="detail-section">
            <h2 class="detail-section__title">推荐收听</h2>
            <ul class="bullet-list">
              <li v-for="(r, idx) in report.recommendations" :key="idx">{{ r }}</li>
            </ul>
          </section>
        </div>

        <!-- SVG 图表: 时段 + 周分布 -->
        <div class="row-2">
          <section class="detail-section">
            <h2 class="detail-section__title">时段分布（24h）</h2>
            <div class="chart-wrap">
              <svg viewBox="0 0 100 72" preserveAspectRatio="none" class="chart-svg">
                <line x1="0" y1="60" x2="100" y2="60" stroke="rgba(255,255,255,0.2)" stroke-width="0.2" />
                <rect
                  v-for="(b, i) in hourlyBars"
                  :key="i"
                  :x="b.x"
                  :y="b.y"
                  width="3.3"
                  :height="b.h"
                  fill="url(#hourlyGrad)"
                  rx="0.4"
                />
                <defs>
                  <linearGradient id="hourlyGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stop-color="#60a5fa" />
                    <stop offset="100%" stop-color="#60a5fa" stop-opacity="0.2" />
                  </linearGradient>
                </defs>
              </svg>
              <div class="chart-axis">
                <span v-for="i in [0, 6, 12, 18, 23]" :key="i">{{ i }}:00</span>
              </div>
            </div>
          </section>

          <section class="detail-section">
            <h2 class="detail-section__title">周分布</h2>
            <div class="chart-wrap">
              <svg viewBox="0 0 100 72" preserveAspectRatio="none" class="chart-svg">
                <line x1="0" y1="60" x2="100" y2="60" stroke="rgba(255,255,255,0.2)" stroke-width="0.2" />
                <rect
                  v-for="(b, i) in weekdayBars"
                  :key="i"
                  :x="b.x"
                  :y="b.y"
                  :width="b.w"
                  :height="b.h"
                  fill="url(#weekGrad)"
                  rx="1"
                />
                <defs>
                  <linearGradient id="weekGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stop-color="#c084fc" />
                    <stop offset="100%" stop-color="#c084fc" stop-opacity="0.2" />
                  </linearGradient>
                </defs>
              </svg>
              <div class="chart-axis">
                <span v-for="(b, i) in weekdayBars" :key="i">周{{ b.label }}</span>
              </div>
            </div>
          </section>
        </div>

        <!-- TOP 榜 -->
        <div class="row-2">
          <section v-if="topTracks.length > 0" class="detail-section">
            <h2 class="detail-section__title">TOP 歌曲</h2>
            <ol class="rank-list">
              <li v-for="(t, idx) in topTracks" :key="idx">
                <span class="rank-num" :class="{ 'is-top': idx < 3 }">{{ idx + 1 }}</span>
                <span class="rank-label">{{ t.name }}</span>
                <span class="rank-value">{{ t.count }} 次</span>
              </li>
            </ol>
          </section>
          <section v-if="topArtists.length > 0" class="detail-section">
            <h2 class="detail-section__title">TOP 歌手</h2>
            <ol class="rank-list">
              <li v-for="(a, idx) in topArtists" :key="idx">
                <span class="rank-num" :class="{ 'is-top': idx < 3 }">{{ idx + 1 }}</span>
                <span class="rank-label">{{ a.name }}</span>
                <span class="rank-value">{{ a.count }} 次</span>
              </li>
            </ol>
          </section>
        </div>

        <!-- 反馈 -->
        <section class="detail-section feedback-section">
          <h2 class="detail-section__title">报告反馈</h2>
          <div class="feedback-row">
            <span class="feedback-label">这份报告怎么样？</span>
            <el-radio-group v-model="feedbackRating">
              <el-radio-button :value="1">
                <el-icon><ThumbsUp /></el-icon> 赞
              </el-radio-button>
              <el-radio-button :value="2">
                <el-icon><ChatLineRound /></el-icon> 踩
              </el-radio-button>
            </el-radio-group>
          </div>
          <el-input
            v-model="feedbackComment"
            type="textarea"
            :rows="3"
            placeholder="（可选）说点什么吧"
            maxlength="500"
            show-word-limit
            class="feedback-textarea"
          />
          <el-button
            type="primary"
            :loading="submitting"
            :disabled="!feedbackRating"
            @click="handleFeedback"
            class="feedback-submit"
          >
            提交反馈
          </el-button>
        </section>
      </template>
    </div>
  </div>
</template>

<style scoped>
.report-detail {
  padding: 24px 32px;
  min-height: 100vh;
  background: linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%);
  color: #e0e7ff;
}

.report-detail__top {
  display: flex;
  justify-content: space-between;
  margin-bottom: 16px;
}

.back-btn {
  color: rgba(224, 231, 255, 0.7);
  font-size: 14px;
}

.report-detail__content {
  max-width: 1100px;
  margin: 0 auto;
}

.report-header {
  padding: 28px 32px;
  background: linear-gradient(135deg, rgba(96, 165, 250, 0.15), rgba(192, 132, 252, 0.15));
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 16px;
  margin-bottom: 20px;
}

.report-header__title {
  margin: 0 0 10px 0;
  font-size: 24px;
  font-weight: 600;
  background: linear-gradient(90deg, #60a5fa, #c084fc);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.report-header__meta {
  margin: 0;
  display: flex;
  align-items: center;
  gap: 12px;
  font-size: 13px;
  color: rgba(224, 231, 255, 0.6);
}

.report-header__pending {
  color: #fbbf24;
  display: inline-flex;
  align-items: center;
  gap: 4px;
}

.is-loading {
  animation: rotate 1.5s linear infinite;
}

@keyframes rotate {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.status-block {
  padding: 48px 24px;
  text-align: center;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 12px;
  margin-bottom: 20px;
}

.status-block h3 {
  margin: 12px 0 8px;
  font-size: 18px;
  color: #e0e7ff;
}

.status-block p {
  margin: 0;
  color: rgba(224, 231, 255, 0.6);
  font-size: 13px;
}

.status-block--pending {
  border-color: rgba(251, 191, 36, 0.4);
  color: #fbbf24;
  font-size: 32px;
}

.status-block--failed {
  border-color: rgba(248, 113, 113, 0.4);
  color: #f87171;
  font-size: 32px;
}

.status-block--empty {
  border-color: rgba(96, 165, 250, 0.3);
  color: #60a5fa;
  font-size: 32px;
}

.row-2 {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  margin-bottom: 16px;
}

.detail-section {
  padding: 22px 26px;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 12px;
  backdrop-filter: blur(10px);
}

.detail-section__title {
  margin: 0 0 14px;
  font-size: 14px;
  font-weight: 600;
  color: rgba(224, 231, 255, 0.85);
  letter-spacing: 1.5px;
  text-transform: uppercase;
  display: flex;
  align-items: center;
}

.detail-section__title::before {
  content: '';
  display: inline-block;
  width: 4px;
  height: 14px;
  background: linear-gradient(180deg, #60a5fa, #c084fc);
  margin-right: 8px;
  border-radius: 2px;
}

.summary-text {
  margin: 0;
  font-size: 15px;
  line-height: 1.8;
  color: #e0e7ff;
  white-space: pre-wrap;
}

.mood-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 12px;
}

.bullet-list {
  margin: 0;
  padding: 0;
  list-style: none;
}

.bullet-list li {
  position: relative;
  padding: 10px 14px 10px 28px;
  margin-bottom: 8px;
  background: rgba(96, 165, 250, 0.08);
  border-left: 3px solid #60a5fa;
  border-radius: 0 6px 6px 0;
  color: #e0e7ff;
  font-size: 13px;
  line-height: 1.6;
}

.bullet-list li::before {
  content: '◆';
  position: absolute;
  left: 10px;
  top: 10px;
  color: #c084fc;
  font-size: 12px;
}

.chart-wrap {
  position: relative;
}

.chart-svg {
  width: 100%;
  height: 180px;
  display: block;
}

.chart-axis {
  display: flex;
  justify-content: space-between;
  padding: 0 4px;
  font-size: 11px;
  color: rgba(224, 231, 255, 0.5);
  margin-top: 4px;
}

.chart-axis span {
  flex: 1;
  text-align: center;
}

.rank-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.rank-list li {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 8px 12px;
  background: rgba(255, 255, 255, 0.03);
  border-radius: 6px;
  transition: background 0.15s;
}

.rank-list li:hover {
  background: rgba(96, 165, 250, 0.08);
}

.rank-num {
  width: 24px;
  height: 24px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: rgba(96, 165, 250, 0.15);
  color: rgba(224, 231, 255, 0.7);
  font-size: 12px;
  font-weight: 700;
  font-family: 'Consolas', monospace;
  border-radius: 4px;
  flex-shrink: 0;
}

.rank-num.is-top {
  background: linear-gradient(135deg, #60a5fa, #c084fc);
  color: #fff;
}

.rank-label {
  flex: 1;
  font-size: 13px;
  color: #e0e7ff;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.rank-value {
  font-size: 13px;
  font-weight: 700;
  color: #60a5fa;
  font-family: 'Consolas', monospace;
  flex-shrink: 0;
}

.feedback-section {
  margin-top: 16px;
}

.feedback-row {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 12px;
}

.feedback-label {
  font-size: 13px;
  color: rgba(224, 231, 255, 0.7);
}

.feedback-textarea {
  margin-bottom: 12px;
}

.feedback-submit {
  margin-top: 4px;
}
</style>